---
title: "Predizendo Se vai chover Amanhã na Australia"
output: html_document
---

```{r include=FALSE}
# install.packages("gmodels")
# install.packages("ggthemes")
# install.packages("ggmap")
# install.packages("sf")
# install.packages("mapview")
# install.packages("ggrepel")
# install.packages("lobstr")
# install.packages("mapproj")
# install.packages("dummies")
# install.packages('caTools')
# install.packages('randomForest')
# install.packages('precrec')

library(tidyverse)
library(gmodels)
library(ggthemes)
library(ggrepel)
library(sf)
library(mapview)
library(ggmap)
library(dummies)
library(caTools)
library(randomForest)
library(precrec)

```

FALAR DOS FOGOS E COMO PREDIZER PODE SER IMPORTANTE PRA REMANEJAR OS ESFORCOS OU SABER SE UM FOCO DE INCENDIO PODE SURGIR

```{r}
dataset = tibble(read.csv('weatherAUS.csv'))
print(dataset)
```


```{r}
MTemp <- dataset[!is.na(dataset$MaxTemp), ] %>% 
  select(Location, MaxTemp)

TempLocation <- aggregate(MTemp$MaxTemp, by=list(Category=MTemp$Location), FUN=mean)
TempLocation$Category <- paste(TempLocation$Category, ", Australia")# Adding Australia to the end of location name since there are many cities with the same names in other countries

```

```{r message=FALSE}
cities_df <- as.data.frame(TempLocation)
locations_df <- mutate_geocode(cities_df, Category)
locations <- as_tibble(locations_df)

locations_sf <- st_as_sf(locations, coords = c("lon", "lat"), crs = 4326)

```



```{r warning=FALSE}
aus_coord <- geocode("Australia")

map <- get_googlemap(center = c(aus_coord$lon, aus_coord$lat), zoom = 4)


ggmap(map) +
  geom_point(data = locations,
             aes(x = lon, y = lat, size = x),
             color = "red", alpha = 0.3)
```



```{r}
RF <- dataset[!is.na(dataset$Rainfall), ] %>% 
  select(Location, Rainfall)

RainLocation <- aggregate(RF$Rainfall, by=list(Category=RF$Location), FUN=sum)
RainLocation$Category <- paste(RainLocation$Category, ", Australia")# Adding Australia to the end of location name since there are many cities with the same names in other countries

```


```{r message=FALSE}
Rcities_df <- as.data.frame(RainLocation)
Rlocations_df <- mutate_geocode(Rcities_df, Category)
Rlocations <- as_tibble(Rlocations_df)

Rlocations_sf <- st_as_sf(Rlocations, coords = c("lon", "lat"), crs = 4326)
print(Rlocations_sf)

```



```{r warning=FALSE}
YlOrBr <- c("#FFFFD4", "#FED98E", "#FE9929", "#D95F0E", "#993404")

ggmap(map) +
  stat_density_2d(
    data = Rlocations,
    aes(x = lon, y = lat, fill = stat(x)),
    alpha = .1,
    bins = 30,
    geom = "polygon"
  ) +
  scale_fill_gradientn(colors = YlOrBr)

```



```{r}
RD <- dataset[!is.na(dataset$Rainfall), ] %>% 
  select(Date, Rainfall)

# substring(RD$Date,6,7) # Month only
RainMonth = aggregate(RD$Rainfall, by=list(Category=substring(RD$Date,6,7)), FUN=mean) # Mean Rainfall by month

```



```{r}
ggplot(data=RainMonth, aes(x=Category, y=x, group=1)) +
  geom_line()+
  geom_point()

```






```{r}
print(colMeans(is.na(dataset))) # Percentage of missing data in each column

datasetClean <- subset(dataset, select=-c(Evaporation, Sunshine, Cloud9am, Cloud3pm, Date)) # Removing features with high NA precentage
datasetClean <- datasetClean[complete.cases(datasetClean), ] # Removing NAs

```

```{r warning=FALSE}
# One-Hot Encoding categorical features

# WD3<-dummy.data.frame(data = datasetClean, dummy.classes = "WindDir3pm")
# Loc<-dummy.data.frame(data = WD3, dummy.classes = "Location")
# WD9<-dummy.data.frame(data = Loc, dummy.classes = "WindDir9am")
# datasetD<- data.frame(dummy.data.frame(data = WD9, dummy.classes = "WindGustDir"))
# 


WD3<-dummy(datasetClean$WindDir3pm)
WD9<-dummy(datasetClean$WindDir9am)
WGD<-dummy(datasetClean$WindGustDir)
Loc<-dummy(datasetClean$Location)


# This is so that Knit doesn't crash (idk why)
colnames(WD3) <- paste("WindDir3pm", colnames(WD3), sep = "_")
colnames(WD9) <- paste("WindDir9am", colnames(WD9), sep = "_")
colnames(WGD) <- paste("WindGustDir", colnames(WGD), sep = "_")
colnames(Loc) <- paste("Location", colnames(Loc), sep = "_")


datasetD <- cbind(datasetClean, WD3)
datasetD <- cbind(datasetD, WD9)
datasetD <- cbind(datasetD, WGD)
datasetD <- cbind(datasetD, Loc)



datasetD$RainToday <- factor(datasetD$RainToday,
             levels = c('No', 'Yes'),
             labels = c(0, 1))

datasetD$RainTomorrow <- factor(datasetD$RainTomorrow,
                   levels = c('No', 'Yes'),
                   labels = c(0, 1))

df<-tibble(datasetD)

```

```{r}
set.seed(1337)

split = sample.split(df$RainTomorrow, SplitRatio = 0.8)
training_set = subset(df, split == TRUE)
test_set = subset(df, split == FALSE)
```

```{r}
y <- training_set$RainTomorrow
X <- subset(training_set, select=-c(RainTomorrow))

classifier = randomForest(x = X,
                          y = y,
                          ntree = 100)

classifier
```

```{r}
y_pred = predict(classifier, newdata = subset(test_set, select=-c(RainTomorrow)))

# Confusion Matrix
cm = table(test_set$RainTomorrow, y_pred)
print(cm)

```

```{r}
# Accuracy Score
accuracy = sum(y_pred == test_set$RainTomorrow) / nrow(test_set)
print(accuracy)
```

```{r}
precrec_obj <- evalmod(scores =as.integer(y_pred), labels = test_set$RainTomorrow)
autoplot(precrec_obj)

```












